In [1]:
import numpy as np

In [2]:
# problem 1
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
common = np.intersect1d(a, b)
print("Distinct common items:", common)

Distinct common items: [2 4]


In [3]:
# problem 2
array = np.arange(1, 16).reshape(5, 3, order='F')
print(array)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [4]:
#problem 3
flattened = array.flatten(order='F')
print(flattened)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [7]:
# problem 4
a_3d = np.stack([array[:, 0], array[:, 1], array[:, 2]], axis=0)
print(a_3d.shape)
print(a_3d)

(3, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
# problem 5
array_2d = a_3d.squeeze().T
print(array_2d)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [11]:
#problem 6
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
filtered_a = np.setdiff1d(a, b)
print(filtered_a)

[ 1  7  8 15]


In [12]:
import pandas as pd
df1 = pd.read_excel("Module6_Data.xlsx")

In [13]:
# 1
max_consumption = df1["NYC Consumption(Million gallons per day)"].max()
print("Maximum yearly NYC consumption (MGD):", max_consumption)

Maximum yearly NYC consumption (MGD): 1512.0


In [14]:
# 2.
num_years = df1.shape[0]
print("Number of calendar years:", num_years)

Number of calendar years: 39


In [15]:
#3
mean_per_capita = df1["Per Capita(Gallons per person per day)"].mean()
std_per_capita = df1["Per Capita(Gallons per person per day)"].std()

print("Mean per capita daily consumption:", mean_per_capita)
print("Standard deviation:", std_per_capita)

Mean per capita daily consumption: 160.30769230769232
Standard deviation: 31.930973122258784


In [16]:
#4 
pop_diff = df1["New York City Population"].diff().dropna()
print("Yearly population change:\n", pop_diff)

Yearly population change:
 1     -30461.0
2      17602.0
3      19864.0
4      72119.0
5      53290.0
6      39540.0
7      45192.0
8      23230.0
9      11243.0
10     -9544.0
11     -8525.0
12     38851.0
13     54443.0
14     77222.0
15     64292.0
16     62582.0
17     64772.0
18     75631.0
19     84816.0
20     89401.0
21     60618.0
22     16685.5
23     16685.5
24     16685.5
25     16685.5
26     16685.5
27     16685.5
28     16685.5
29     16685.5
30     16685.5
31     16685.5
32    108965.0
33     77081.0
34     61281.0
35     49530.0
36     44512.0
37     21171.0
38     85025.0
Name: New York City Population, dtype: float64
